import type { Metadata } from "next";
import { Fira_Sans, Hedvig_Letters_Serif } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

const firaSans = Fira_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

const hedvig = Hedvig_Letters_Serif({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${firaSans.variable} ${hedvig.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-linear-to-tr from-black to-[#171717]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
